name: CI Pipeline - Music Analyzer

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t davmano/music-analyzer:v1 .
        docker push davmano/music-analyzer:v1

    - name: Update K8s Deployment with new image tag
      run: |
        sed -i 's|image: davmano/music-analyzer:.*|image: davmano/music-analyzer:v1|' k8s/deployment.yaml

    - name: Commit updated manifest
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add k8s/deployment.yaml
        git commit -m "Update image tag to v1" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/davmano/Music_Analyser.git HEAD:main

